services:
  nginx-waf:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "80:8080"
      # only available if SETTLS was enabled:
      - "443:8443"
    volumes:
      - ./modsecurity.conf:/etc/nginx/modsec/modsecurity.conf
    restart: always